# config.py
import math

# --- 1. Define Physics Parameters ---
# config.py
PARAMS = {
    "PARAM_N_NEURONS": 10e9, # neuron number
    "PARAM_T_MAX":     1000.0, # simulation time (ms)
    "PARAM_TAU":       10.0, # membrane time constant (ms)
    "PARAM_MU":        1.2, # drift
    "PARAM_D":         0.01, # noise strength
    "PARAM_V_TH":      1.0, # threshold
    "PARAM_V_RESET":   0.0, # reset potential
    "PARAM_DT_NET":    0.02, # network time step size
    "PARAM_GRID_N":    400  # FPE grid
}

# --- 2. Generate C Header ---
def generate_c_header():
    header_content = "#ifndef PARAMS_H\n#define PARAMS_H\n\n"
    header_content += "// Auto-generated by config.py. DO NOT EDIT.\n\n"
    
    for key, val in PARAMS.items():
        # C uses simple text replacement for defines
        if isinstance(val, int):
            header_content += f"#define {key} {val}\n"
        else:
            header_content += f"#define {key} {val}\n"
            
    header_content += "\n#endif\n"
    
    with open("params.h", "w") as f:
        f.write(header_content)
    print("✓ Generated params.h")

if __name__ == "__main__":
    generate_c_header()