# config.py
import math

# --- 1. Define Physics Parameters ---
PARAMS = {
    "N_NEURONS": 500,       # Size of network
    "T_MAX":     1000.0,    # Total time (ms)
    "TAU":       10.0,      # Membrane time constant (ms)
    "MU":        1.2,       # Drift (Fluctuation regime < 1.0)
    "D":         0.02,      # Noise strength
    "V_TH":      1.0,       # Threshold
    "V_RESET":   0.0,       # Reset potential
    "DT_NET":    0.02,      # Network Sim time step (ms) - TUNED value
    "GRID_N":    400        # FPE Grid Size
}

# --- 2. Generate C Header ---
def generate_c_header():
    header_content = "#ifndef PARAMS_H\n#define PARAMS_H\n\n"
    header_content += "// Auto-generated by config.py. DO NOT EDIT.\n\n"
    
    for key, val in PARAMS.items():
        # C uses simple text replacement for defines
        if isinstance(val, int):
            header_content += f"#define {key} {val}\n"
        else:
            header_content += f"#define {key} {val}\n"
            
    header_content += "\n#endif\n"
    
    with open("params.h", "w") as f:
        f.write(header_content)
    print("✓ Generated params.h")

if __name__ == "__main__":
    generate_c_header()