"""Compute side of the publication figures.

One run = one invocation of the C solver with its own parameter header,
executed in a throw-away working directory so the project's own data/ and
src/params.h are never touched. The multi-gigabyte raw output is reduced
immediately to a small .npz in publication/cache/ and then deleted.

Everything expensive lives here. The fig_*.py scripts only read the cache,
so restyling a figure never costs a simulation.
"""

import os
import shutil
import subprocess
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, "cache")
WORK = os.path.join(CACHE, "_work")

for _path in (PROJECT, HERE):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from analysis.lif import cv_benji, rate_whitenoise_benji      # noqa: E402
from analysis.utils import log_smooth                          # noqa: E402

import configs                                                 # noqa: E402


# ==========================================================================
# Parameter header
# ==========================================================================
def derived(params):
    """CV and stationary rate, exactly as config.py computes them."""
    cv = cv_benji(params["MU"], params["D"])
    r0 = rate_whitenoise_benji(params["MU"], np.sqrt(params["D"]))
    return cv, r0


def write_header(path, params):
    cv, r0 = derived(params)
    full = dict(params)
    full["CV"] = cv
    full["R0"] = r0

    lines = ["#ifndef PARAMS_H", "#define PARAMS_H", "",
             "// Generated by publication/pipeline.py", ""]
    for key, val in full.items():
        if isinstance(val, int) and not isinstance(val, bool):
            lines.append(f"#define PARAM_{key} {val}")
        else:
            lines.append(f"#define PARAM_{key} {float(val):.8f}")
    lines += ["", "#endif", ""]

    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return cv, r0


# ==========================================================================
# Solver
# ==========================================================================
# Wall-clock of the most recent solver execution, excluding compilation.
# Filled by run_solver so the benchmark can time the solver without
# reimplementing the build.
LAST_RUN = {}


def run_solver(tag, params, verbose=True, patches=None):
    """Build and run the C solver for one parameter set.

    `patches` is an optional list of (old, new) string pairs applied to the
    copy of the solver source. It exists for numerical experiments on
    constants that are hard-coded in the C file, and it never touches the
    project's own source. A pattern that does not match is an error rather
    than a silent no-op.

    Returns the working directory holding data/activity.bin and
    data/density.bin. The caller is responsible for cleaning it up.
    """
    workdir = os.path.join(WORK, tag)
    shutil.rmtree(workdir, ignore_errors=True)
    os.makedirs(workdir, exist_ok=True)

    # The solver reads src/lambda_table.bin relative to its working
    # directory, so point a link at the project's src/.
    os.symlink(os.path.join(PROJECT, "src"), os.path.join(workdir, "src"))

    # Copying the source next to our own params.h makes the quoted include
    # resolve here rather than to src/params.h.
    source = os.path.join(PROJECT, "src", "stochastic_fpe.c")
    text = open(source).read()
    for old, new in (patches or []):
        if old not in text:
            raise ValueError(f"patch target not found in solver source: {old!r}")
        text = text.replace(old, new)
        if verbose:
            print(f"  patched: {old.strip()}  ->  {new.strip()}")
    with open(os.path.join(workdir, "stochastic_fpe.c"), "w") as fh:
        fh.write(text)
    write_header(os.path.join(workdir, "params.h"), params)

    binary = os.path.join(workdir, "solver")
    compile_cmd = ["gcc", "stochastic_fpe.c", "-o", "solver",
                   "-O3", "-Wall", "-lm", "-march=native", "-flto"]
    if verbose:
        print(f"  compiling {tag} ...")
    subprocess.run(compile_cmd, cwd=workdir, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

    if verbose:
        print(f"  running solver ({configs.describe_params(params)}) ...")
    t0 = time.time()
    proc = subprocess.run([binary], cwd=workdir, check=True,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          text=True)
    LAST_RUN["seconds"] = time.time() - t0
    LAST_RUN["tag"] = tag
    if verbose:
        tail = proc.stdout.strip().splitlines()
        print(f"  solver finished in {time.time() - t0:.0f} s")
        for line in tail[:2]:
            print(f"    {line}")

    return workdir


# ==========================================================================
# Spectral estimation
# ==========================================================================
def periodogram_welch_free(data, dt, df=1.0):
    """Bartlett periodogram, accumulated one segment at a time.

    Numerically identical to analysis.utils.periodogram but never holds more
    than a single segment in memory, which matters because a 40 s run is
    ~10^8 samples. Uses rfft since only the positive half is returned.
    """
    nfft = int(1.0 / (dt * df) + 0.5)
    df_out = 1.0 / (nfft * dt)
    ntrials = int(len(data) / nfft)
    if ntrials < 1:
        raise ValueError(
            f"series too short: {len(data)} samples < NFFT {nfft}")

    keep = nfft // 2
    acc = np.zeros(keep - 1, dtype=np.float64)
    for k in range(ntrials):
        seg = np.asarray(data[k * nfft:(k + 1) * nfft], dtype=np.float64)
        spec = np.fft.rfft(seg)[1:keep]
        acc += (spec.real ** 2 + spec.imag ** 2)

    psd = acc * dt / (nfft - 1) / ntrials
    freq = df_out * np.arange(keep - 1) + df_out
    return freq, psd


def spectrum(activity_hz, dt_sec, bins_per_decade=20, skip_ms=0.0):
    """Spectrum of the stationary part of a trace.

    `skip_ms` discards the start before estimating. This matters more than it
    looks: the Bartlett segments are one second long, so any startup
    transient lands wholly inside the first segment and is averaged over only
    the number of segments. A rate step of a few hundred Hz lasting tens of
    milliseconds carries orders of magnitude more low-frequency power than
    the finite-size plateau being measured, and silently inflates it.
    """
    if skip_ms > 0.0:
        skip = int(skip_ms / 1000.0 / dt_sec)
        activity_hz = activity_hz[skip:]
    freq, psd = periodogram_welch_free(activity_hz, dt_sec, df=1.0)
    return log_smooth(freq, psd, bins_per_decade=bins_per_decade)


# ==========================================================================
# Microscopic reference network
# ==========================================================================
# Euler-Maruyama only tests the threshold at sample points, so a path that
# crosses and returns inside one step is never counted. The reference network
# therefore fires too slowly, and the whole activity spectrum sits low by the
# same factor, since its high-frequency plateau is just the rate over N. The
# deficit scales as sqrt(dt) and is worst where firing is noise-driven: 7.5%
# subthreshold at low noise against 1.3% suprathreshold.
#
# The remedy is detection, not refinement. Given both endpoints below the
# threshold b and increment variance s2, a Brownian bridge crossed with
# probability exp(-2 (b - v0)(b - v1) / s2). Drawing against that restores
# first-order convergence of the hitting time, and costs one exponential and
# one uniform per step rather than the sixteen-fold step refinement that would
# be needed to get even half as close. Measured against the exact rate:
#
#   subthreshold  low noise    -7.45%  ->  +0.43%
#   suprathreshold low noise   -1.27%  ->  +0.10%
#
# Refining on top of the correction moves it only to +0.24% and +0.03%, so
# what is left is no longer crossing bias.
MICRO_BRIDGE = True


def run_micro(params, t_max_ms, seed=1, verbose=True, bridge=None):
    """N uncoupled/coupled LIF Langevin neurons, Euler-Maruyama.

    Port of validation.check_psd.run_network, minus the per-neuron spike-time
    bookkeeping that the spectrum does not use, plus the Brownian-bridge exit
    correction described at MICRO_BRIDGE. Pass bridge=False for the
    uncorrected scheme.
    """
    rng = np.random.default_rng(seed)
    # Separate stream for the bridge draws, so switching the correction on
    # leaves the Gaussian increments bit-identical to an uncorrected run.
    aux = np.random.default_rng(seed + 90_000)
    if bridge is None:
        bridge = MICRO_BRIDGE

    n = int(params["N_NEURONS"])
    mu = params["MU"]
    d = params["D"]
    tau = params["TAU"]
    v_th = params["V_TH"]
    v_reset = params["V_RESET"]
    dt = params["DT_NET"]
    w = params["W"]
    p = params["CONNECTIVITY"]
    delay = params["DELAY"]
    recurrent = bool(params["RECURRENCE"]) and w != 0.0

    steps = int(t_max_ms / dt)
    dt_sec = dt / 1000.0
    activity = np.zeros(steps, dtype=np.float32)

    buffer_size = int(delay / dt) + 1
    spike_buffer = np.zeros((buffer_size, n), dtype=np.float32)

    # Sparse storage once the connectivity is dilute: a dense N-by-N matrix
    # is what stops the interesting regime from being reachable at all, since
    # separating random from full connectivity needs few inputs per neuron
    # while keeping the feedback noise low needs a large population.
    conn = None
    sparse_conn = None
    if recurrent and p < 1.0:
        if p <= 0.2 and n >= 1000:
            from scipy import sparse as _sp
            sparse_conn = _sp.random(
                n, n, density=p, format="csr", random_state=rng,
                data_rvs=lambda size: np.full(size, w / p, dtype=np.float32),
                dtype=np.float32)
            if verbose:
                print(f"    sparse connectivity: {sparse_conn.nnz:,} "
                      f"synapses, {sparse_conn.nnz / n:.0f} per neuron")
        else:
            conn = (rng.random((n, n)) < p).astype(np.float32) * (w / p)

    v = np.zeros(n)
    drift_factor = dt / tau
    noise_factor = np.sqrt(2.0 * d / tau) * np.sqrt(dt)
    step_var = noise_factor * noise_factor

    if verbose:
        kind = ("all-to-all" if p >= 1.0 else f"random p={p:g}") \
            if recurrent else "unconnected"
        print(f"  microscopic network: N={n}, {steps:,} steps, {kind}"
              + (", bridge-corrected" if bridge else ""))

    write_idx = 0
    report = max(1, steps // 20)
    t0 = time.time()

    for i in range(steps):
        kick = 0.0
        if recurrent:
            delayed = spike_buffer[(write_idx + 1) % buffer_size]
            if p >= 1.0:
                kick = ((w / n) / tau) * delayed.sum()
            elif sparse_conn is not None:
                kick = (sparse_conn @ delayed) / n / tau
            else:
                kick = (conn @ delayed) / n / tau

        v_old = v
        v = v_old + (mu - v_old) * drift_factor \
            + rng.standard_normal(n) * noise_factor + kick

        spikes = v >= v_th
        if bridge:
            below = ~spikes
            gap = (v_th - v_old[below]) * (v_th - v[below])
            crossed = aux.random(below.sum()) < np.exp(-2.0 * gap / step_var)
            spikes[np.flatnonzero(below)[crossed]] = True
        v = np.where(spikes, v_reset, v)
        activity[i] = spikes.sum() / (n * dt_sec)

        if recurrent:
            spike_buffer[write_idx] = spikes
        write_idx = (write_idx + 1) % buffer_size

        if verbose and i % report == 0 and i:
            frac = i / steps
            eta = (time.time() - t0) * (1.0 / frac - 1.0)
            print(f"    {frac * 100:3.0f}%  eta {eta:5.0f} s", end="\r",
                  flush=True)

    if verbose:
        print(f"    microscopic network done in {time.time() - t0:.0f} s"
              + " " * 20)
    return activity


# ==========================================================================
# Analytical finite-size spectrum
# ==========================================================================
def exact_spectrum(freqs_hz, params, rate_hz):
    from analysis.lif_susceptibility_psd import get_theoretical_curve
    return get_theoretical_curve(
        freqs_hz, params["MU"], params["D"], params["TAU"],
        params["V_TH"], params["V_RESET"], rate_hz, params["N_NEURONS"])


# ==========================================================================
# Reduction: raw binaries -> cache entry
# ==========================================================================
def downsample(x, target):
    step = max(1, len(x) // target)
    return np.asarray(x[::step], dtype=np.float64), step


def moving_average(x, window):
    """Centred moving average with the invalid edges set to NaN.

    'same'-mode convolution tapers towards zero at both ends, which shows up
    as a fake dive at t=0 and t=T. NaN-ing those samples makes matplotlib
    skip them instead of drawing the artefact.
    """
    if window < 2:
        return np.asarray(x, dtype=np.float64)
    kernel = np.ones(window) / window
    out = np.convolve(x, kernel, mode="same").astype(np.float64)
    out[:window] = np.nan
    out[-window:] = np.nan
    return out


def reduce_run(tag, params, workdir, want_micro, want_exact,
               trace_points=40000, n_snapshots=6, verbose=True):
    """Turn the raw solver output into the compact arrays a figure needs."""
    grid_n = int(params["GRID_N"])
    t_max = params["T_MAX"]

    act = np.memmap(os.path.join(workdir, "data", "activity.bin"),
                    dtype=np.float32, mode="r").reshape(-1, 2)
    dens = np.memmap(os.path.join(workdir, "data", "density.bin"),
                     dtype=np.float32, mode="r").reshape(-1, grid_n)

    n_steps = act.shape[0]
    dt_ms = t_max / n_steps
    dt_sec = dt_ms / 1000.0

    out = {
        "tag": tag,
        "label": configs.describe_params(params),
        "t_max_ms": t_max,
        "n_steps": n_steps,
        "dt_ms": dt_ms,
        "grid_n": grid_n,
    }
    for key, val in params.items():
        out[f"param_{key}"] = val

    # --- voltage grid -----------------------------------------------------
    dx = (configs.V_MAX - configs.V_MIN) / grid_n
    out["v_grid"] = configs.V_MIN + dx * np.arange(grid_n)
    out["dx"] = dx

    # --- density ----------------------------------------------------------
    n_snap = dens.shape[0]
    idx = np.linspace(0, n_snap - 1, n_snapshots, dtype=int)
    out["density_snapshots"] = np.asarray(dens[idx], dtype=np.float64)
    out["density_times_ms"] = idx * (t_max / n_snap)
    # Stationary density: average over the second half of the run.
    half = n_snap // 2
    out["density_stationary"] = np.asarray(
        dens[half:], dtype=np.float64).mean(axis=0)

    # --- rate and mass traces --------------------------------------------
    rate_ds, step = downsample(act[:, 0], trace_points)
    rate_ds *= 1000.0                      # kHz -> Hz
    mass_ds, _ = downsample(act[:, 1], trace_points)
    t_ds = np.linspace(0.0, t_max, len(rate_ds))

    out["t_ms"] = t_ds
    out["rate_hz"] = rate_ds
    out["mass"] = mass_ds
    out["downsample_step"] = step

    dt_ds_ms = t_max / len(rate_ds)
    out["rate_hz_smooth10"] = moving_average(
        rate_ds, max(1, int(10.0 / dt_ds_ms)))
    out["mass_smooth100"] = moving_average(
        mass_ds, max(1, int(100.0 / dt_ds_ms)))
    out["smooth_window_bins"] = max(1, int(10.0 / dt_ds_ms))
    out["mass_window_bins"] = max(1, int(100.0 / dt_ds_ms))

    # A short window at full time resolution, taken from the stationary part
    # of the run. The downsampled trace above is fine for showing 40 s of
    # stationarity but averages away the structure of A(t); panels that need
    # to show what the activity actually looks like use this instead.
    excerpt_ms = 100.0
    start = int(0.6 * n_steps)
    count = int(min(excerpt_ms / dt_ms, n_steps - start))
    out["excerpt_t_ms"] = dt_ms * np.arange(count)
    out["excerpt_rate_hz"] = np.asarray(
        act[start:start + count, 0], dtype=np.float64) * 1000.0
    out["excerpt_mass"] = np.asarray(
        act[start:start + count, 1], dtype=np.float64)
    out["excerpt_dt_ms"] = dt_ms
    out["excerpt_start_ms"] = start * dt_ms

    # Statistics over the full-resolution series, skipping a 30% transient.
    stride = max(1, n_steps // 2_000_000)
    tail = np.asarray(act[int(0.3 * n_steps)::stride, :], dtype=np.float64)
    out["rate_mean_hz"] = float(tail[:, 0].mean() * 1000.0)
    out["mass_mean"] = float(tail[:, 1].mean())
    out["mass_final"] = float(act[-1, 1])

    # Reference stationary rate (Siegert).
    mu_dim = (params["MU"] - params["V_RESET"]) / \
        (params["V_TH"] - params["V_RESET"])
    sigma_dim = np.sqrt(params["D"]) / (params["V_TH"] - params["V_RESET"])
    rate_siegert = rate_whitenoise_benji(mu_dim, sigma_dim) * \
        (1000.0 / params["TAU"])
    out["rate_siegert_hz"] = float(rate_siegert)
    cv, _ = derived(params)
    out["cv"] = float(cv)

    # --- spectra ----------------------------------------------------------
    # Only worth computing when the run is long enough and did not collapse.
    if t_max >= 20000.0:
        if verbose:
            print("  spectrum of solver output ...")
        activity_hz = np.asarray(act[:, 0], dtype=np.float64) * 1000.0
        f_meso, p_meso = spectrum(activity_hz, dt_sec)
        del activity_hz
        out["freq_meso"] = f_meso
        out["psd_meso"] = p_meso

        if want_micro:
            micro = run_micro(params, t_max, verbose=verbose)
            f_mic, p_mic = spectrum(micro.astype(np.float64),
                                    params["DT_NET"] / 1000.0)
            out["freq_micro"] = f_mic
            out["psd_micro"] = p_mic
            out["micro_rate_mean_hz"] = float(micro.mean())
            del micro

        if want_exact:
            if verbose:
                print("  analytical spectrum ...")
            # The theory is a ratio of parabolic cylinder functions and
            # stays numerically flat and stable out to 400 kHz, and costs a
            # third of a second for a whole grid, so there is no reason to
            # truncate it. The old 2500 Hz cap left the analytical curve
            # dangling part-way across the panel.
            mask = f_meso > 0.5
            f_th = f_meso[mask]
            out["freq_exact"] = f_th
            out["psd_exact"] = exact_spectrum(f_th, params, rate_siegert)
            out["psd_poisson_level"] = rate_siegert / params["N_NEURONS"]
            out["psd_lowfreq_level"] = \
                rate_siegert * cv ** 2 / params["N_NEURONS"]

    return out


def deviation_metrics(f_ref, p_ref, f_test, p_test, f_min=1.0, f_max=10000.0):
    """Log-spectral distance and relative RMSE of `test` against `ref`."""
    mask = (f_test >= f_min) & (f_test <= f_max)
    f_eval = f_test[mask]
    p_eval = p_test[mask]
    p_interp = np.interp(f_eval, f_ref, p_ref)
    lsd = float(np.sqrt(np.mean((np.log10(p_interp)
                                 - np.log10(p_eval)) ** 2)))
    rmse = float(np.sqrt(np.mean((p_interp - p_eval) ** 2)))
    return lsd, rmse / float(np.mean(p_eval))


# ==========================================================================
# Cache front end
# ==========================================================================
def cache_path(tag):
    return os.path.join(CACHE, f"{tag}.npz")


def ensure(tag, force=False, keep_raw=False, verbose=True):
    """Return the cached arrays for `tag`, computing them if needed."""
    path = cache_path(tag)
    if os.path.exists(path) and not force:
        if verbose:
            print(f"[cache] {tag}")
        return np.load(path, allow_pickle=True)

    params = configs.RUNS[tag]
    print(f"[compute] {tag}: {configs.describe(tag)}")
    os.makedirs(CACHE, exist_ok=True)

    workdir = run_solver(tag, params, verbose=verbose)
    try:
        data = reduce_run(tag, params, workdir,
                          want_micro=configs.needs_micro(tag),
                          want_exact=configs.needs_exact(tag),
                          verbose=verbose)
        np.savez_compressed(path, **data)
        size_mb = os.path.getsize(path) / 1e6
        print(f"  cached -> {path} ({size_mb:.1f} MB)")
    finally:
        if not keep_raw:
            shutil.rmtree(workdir, ignore_errors=True)

    return np.load(path, allow_pickle=True)


def load(tag):
    path = cache_path(tag)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"no cache for '{tag}'. Run: python publication/make.py compute "
            f"--only {tag}")
    return np.load(path, allow_pickle=True)


def val(data, key, default=None):
    """Read a scalar out of a loaded .npz (they come back as 0-d arrays)."""
    if key not in data:
        return default
    arr = data[key]
    return arr.item() if arr.ndim == 0 else arr


# ==========================================================================
# Ensemble runs: several independent realisations of the same condition
# ==========================================================================
# Run-to-run scatter in the low-frequency plateau is about 3%, which is the
# same size as several of the effects worth reporting. A single realisation
# therefore cannot support a claim at that level, so the spectra in the
# figures are means over independent seeds with a band showing the spread.

def seed_patch(seed):
    """Inject an RNG seed. The solver never calls srand(), so without this
    every run replays the identical noise realisation."""
    return [("// seed_rng((uint64_t)time(NULL));", f"srand({seed});")]


def ensemble_path(tag):
    return os.path.join(CACHE, f"{tag}_ens.npz")


def ensemble(tag, force=False, verbose=True):
    """Compute (or load) the multi-seed spectra for one run."""
    path = ensemble_path(tag)
    if os.path.exists(path) and not force:
        if verbose:
            print(f"[cache] {tag} ensemble")
        return np.load(path, allow_pickle=True)

    params = configs.RUNS[tag]
    base_patches = configs.patches_for(tag)
    want_micro = configs.needs_micro(tag)
    want_exact = configs.needs_exact(tag)

    seeds = configs.seeds_for(tag)
    micro_bridge = configs.micro_bridge_for(tag)
    print(f"[ensemble] {tag}: {configs.describe(tag)}"
          f"  ({len(seeds)} seeds)")
    os.makedirs(CACHE, exist_ok=True)

    psd_meso, psd_micro = [], []
    rate_meso, rate_micro, mass_meso = [], [], []
    freq_meso = freq_micro = None

    for seed in seeds:
        print(f"\n  --- seed {seed} ---")
        workdir = run_solver(f"ens_{tag}_{seed}", params, verbose=verbose,
                             patches=base_patches + seed_patch(seed))
        try:
            act = np.memmap(os.path.join(workdir, "data", "activity.bin"),
                            dtype=np.float32, mode="r").reshape(-1, 2)
            n = act.shape[0]
            dt_ms = params["T_MAX"] / n
            activity = np.asarray(act[:, 0], dtype=np.float64) * 1000.0
            f, p = spectrum(activity, dt_ms / 1000.0,
                            skip_ms=configs.SPECTRUM_SKIP_MS)
            freq_meso = f if freq_meso is None else freq_meso
            psd_meso.append(p)
            rate_meso.append(float(activity[n // 3:].mean()))
            mass_meso.append(float(np.asarray(
                act[n // 3::max(1, n // 500_000), 1], dtype=np.float64).mean()))
            del activity
        finally:
            shutil.rmtree(workdir, ignore_errors=True)

        if want_micro:
            micro = run_micro(params, params["T_MAX"], seed=seed,
                              verbose=verbose, bridge=micro_bridge)
            f, p = spectrum(micro.astype(np.float64),
                            params["DT_NET"] / 1000.0,
                            skip_ms=configs.SPECTRUM_SKIP_MS)
            freq_micro = f if freq_micro is None else freq_micro
            psd_micro.append(p)
            rate_micro.append(float(micro.mean()))
            del micro

    out = {
        "tag": tag,
        "seeds": np.array(seeds),
        "dt_ms": params["T_MAX"] / n,
        "freq_meso": freq_meso,
        "psd_meso_all": np.vstack(psd_meso),
        "rate_meso": np.array(rate_meso),
        "mass_meso": np.array(mass_meso),
        "patched": bool(base_patches),
    }
    for key, v in params.items():
        out[f"param_{key}"] = v

    if want_micro:
        out["freq_micro"] = freq_micro
        out["psd_micro_all"] = np.vstack(psd_micro)
        out["rate_micro"] = np.array(rate_micro)

    # Reference quantities
    mu_dim = (params["MU"] - params["V_RESET"]) / \
        (params["V_TH"] - params["V_RESET"])
    sigma_dim = np.sqrt(params["D"]) / (params["V_TH"] - params["V_RESET"])
    rate_siegert = rate_whitenoise_benji(mu_dim, sigma_dim) * \
        (1000.0 / params["TAU"])
    cv, _ = derived(params)
    out["rate_siegert_hz"] = float(rate_siegert)
    out["cv"] = float(cv)

    if want_exact:
        # Same as above: no cap, the theory is stable and cheap.
        mask = freq_meso > 0.5
        f_th = freq_meso[mask]
        out["freq_exact"] = f_th
        out["psd_exact"] = exact_spectrum(f_th, params, rate_siegert)
        out["psd_poisson_level"] = rate_siegert / params["N_NEURONS"]
        out["psd_lowfreq_level"] = rate_siegert * cv ** 2 / params["N_NEURONS"]

    np.savez_compressed(path, **out)
    print(f"\n  cached -> {path} ({os.path.getsize(path) / 1e6:.1f} MB)")
    return np.load(path, allow_pickle=True)


def load_ensemble(tag):
    path = ensemble_path(tag)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"no ensemble for '{tag}'. Run: python publication/make.py "
            f"ensemble --only {tag}")
    return np.load(path, allow_pickle=True)


def mean_band(psd_all, n_sd=1.0):
    """Mean spectrum across seeds and a +/- n_sd band, clipped positive."""
    mean = psd_all.mean(axis=0)
    sd = psd_all.std(axis=0, ddof=1)
    lo = np.clip(mean - n_sd * sd, 1e-30, None)
    return mean, lo, mean + n_sd * sd
